version: '3'

services:
  database-mysql:
    restart: always
    image: mysql:5.7
    volumes:
    - ./data/db-mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=<db-root-pw>
    - MYSQL_DATABASE=minecraft
    - MYSQL_USER=minecraft
    - MYSQL_PASSWORD=<db-user-pw>

  database-mongo:
    restart: always
    image: frodenas/mongodb:3.0
    volumes:
    - ./data/db-mongo:/data
    environment:
    - MONGODB_DBNAME=cubeengine
    - MONGODB_USERNAME=minecraft
    - MONGODB_PASSWORD=<mongo-db-user-pw>

  forge:
    restart: always
    image: cubeengine/forge:latest
    depends_on:
    - database-mysql
    - database-mongo
    volumes:
    - ./data/root:/home/minecraft/server/root
    - ./data/world:/home/minecraft/server/world
    - ./data/config:/home/minecraft/server/config
    - ./data/logs:/home/minecraft/server/logs
    - ./data/mods:/home/minecraft/server/mods
    ports:
    - "25565:25565"
    - "25575:25575"
    environment:
    - CE_PLUGINS=backpack bigdata chat conomy controlc docs elevator fun hide itemrepair kickban kits locker multiverse namehistory portals powertools protector roles selector shout signmarket spawn spawner squelch teleport travel vanillaplus vigil worlds writer
    - DB_HOST=database-mysql
    - DB_PASSWORD=<db-user-pw>
    - MONGO_DB_HOST=database-mongo
    - MONGO_DB_PASSWORD=<mongo-db-user-pw>
    - ENABLE_RCON=true
    - RCON_PASSWORD=<rcon-pw>
    - JAVA_VM_ARGS=-Xmx2G
